# Generated by Django 3.2.3 on 2021-05-30 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djangoclasses',
            old_name='Title',
            new_name='title',
        ),
    ]
