# Generated by Django 3.2.3 on 2021-05-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_rename_title_djangoclasses_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangoclasses',
            name='Duration',
        ),
    ]
